import { Geist, Geist_Mono, Open_Sans, Montserrat } from "next/font/google";
import { Providers } from "./Providers";
import "./globals.css";
import Header from "@/components/Header";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const openSans = Open_Sans({
	variable: "--font-open-sans",
	subsets: ["latin"],
});

const montserratSans = Montserrat({
    variable: "--font-montserrat-sans",
    subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={` ${montserratSans.variable} ${openSans.variable} ${geistSans.variable} ${geistMono.variable} antialiased `}>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
